# Generated by Django 5.1.3 on 2024-11-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_comment_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
